name: deploy-auth

on:
  push:
    branches:
      - main
    paths:
      - 'auth/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out GitHub codes
        uses: actions/checkout@v2
      - name: Log in to Docker
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build image
        run: cd auth && docker build -t ducanhle1992/auth .
      - name: Push image
        run: docker push ducanhle1992/auth
