name: deploy-auth

on:
  push:
    branches:
      - main
    paths:
      - "auth/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Login to Docker
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build image
        run: cd auth && docker build -t ducanhle1992/auth .
      - name: Push image
        run: docker push ducanhle1992/auth
      - name: Setup UpCloud CLI
        uses: upcloudltd/upcloud-cli-action@main
        with:
          username: ${{ secrets.UPCLOUD_USERNAME }}
          password: ${{ secrets.UPCLOUD_PASSWORD }}
      - name: Setup kubeconfig
        run: upctl kubernetes config 0de978bb-de63-4284-b1e4-6673808fb193 --write ticket-booking-app_kubeconfig.yaml && export KUBECONFIG=$(pwd)/ticket-booking-app_kubeconfig.yaml
      - name: Restart deployment
        run: kubectl rollout restart deployment auth-depl
