name: deploy-payments

on:
  push:
    branches:
      - main
    paths:
      - "payments/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Login to Docker
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build image
        run: cd payments && docker build -t ducanhle1992/payments .
      - name: Push image
        run: docker push ducanhle1992/payments
      - name: Setup DigitalOcean CLI
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_TOKEN }}
      - name: Setup DigitalOcean in kubeconfig
        run: doctl kubernetes cluster kubeconfig save ticket-system
      - name: Restart deployment
        run: kubectl rollout restart deployment payments-depl
